"""Compose a MuJoCo scene: SO-101 arm + a desk plane + captured real objects.

    python3 tools/build_sim_scene.py water_bottle [more_objects...] [--out sim/desk_scene.xml]

Objects must already be processed by tools/make_object.py (which writes
sim/objects/<name>/). The scene is written next to sim/so101/ so that the arm's
`meshdir="assets"` keeps resolving, and object meshes are referenced relatively.
"""
import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("objects", nargs="+")
    ap.add_argument("--out", default="sim/so101/desk_scene.xml")
    ap.add_argument("--desk-height", type=float, default=0.0,
                    help="Z of the work surface the arm and objects sit on")
    args = ap.parse_args()

    assets, bodies = [], []
    for i, name in enumerate(args.objects):
        obj_dir = REPO / "sim" / "objects" / name
        manifest_path = obj_dir / f"{name}.json"
        if not manifest_path.exists():
            raise SystemExit(f"missing {manifest_path} — run tools/make_object.py first")
        man = json.loads(manifest_path.read_text())
        # mesh paths resolve against the arm's compiler meshdir="assets", i.e.
        # sim/so101/assets/ — so climb two levels to reach sim/objects/
        rel = f"../../objects/{name}"

        assets.append(f'    <mesh name="{name}_visual" file="{rel}/visual.obj"/>')
        geoms = [f'      <geom type="mesh" mesh="{name}_visual" class="obj_visual"/>']
        for h in range(man["convex_hulls"]):
            assets.append(f'    <mesh name="{name}_c{h}" file="{rel}/collision_{h:02d}.obj"/>')
            geoms.append(
                f'      <geom type="mesh" mesh="{name}_c{h}" class="obj_collision" '
                f'friction="{man["friction"]} 0.01 0.001"/>'
            )
        if not man["convex_hulls"]:
            geoms.append('      <geom type="box" size="0.03 0.03 0.03" class="obj_collision"/>')

        # lay objects out in front of the arm, spaced along X. The mesh origin is
        # the object's BASE, so rest it on the surface with a hair of clearance —
        # dropping it from any height makes it skitter before the episode starts.
        x = 0.20 + 0.12 * i
        z = args.desk_height + 0.002
        inertia = man.get("diaginertia", [4e-4, 4e-4, 2e-4])
        bodies.append(f"""    <body name="{name}" pos="{x:.3f} 0 {z:.3f}">
      <freejoint name="{name}_free"/>
      <inertial pos="0 0 {man.get('com_z_m', 0.05):.4f}" mass="{man['mass_kg']:.4f}"
                diaginertia="{' '.join(f'{v:.6f}' for v in inertia)}"/>
{chr(10).join(geoms)}
    </body>""")

    xml = f"""<mujoco model="so101_desk_scene">
  <!-- generated by tools/build_sim_scene.py -->
  <include file="so101_new_calib.xml"/>

  <statistic center="0.2 0 0.1" extent="0.8"/>
  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.35 0.35 0.35" specular="0 0 0"/>
    <global azimuth="150" elevation="-25" offwidth="1280" offheight="720"/>
  </visual>

  <default>
    <default class="obj_visual">
      <geom group="2" contype="0" conaffinity="0" density="0"/>
    </default>
    <default class="obj_collision">
      <geom group="3" condim="4" solref="0.004 1"/>
    </default>
  </default>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.25 0.35 0.45" rgb2="0 0 0" width="512" height="1024"/>
    <texture type="2d" name="desk" builtin="checker" rgb1="0.68 0.6 0.47" rgb2="0.6 0.52 0.4" width="300" height="300"/>
    <material name="desk" texture="desk" texuniform="true" texrepeat="8 8" reflectance="0.05"/>
{chr(10).join(assets)}
  </asset>

  <worldbody>
    <light pos="0.3 0 1.4" dir="0 0 -1" directional="true"/>
    <geom name="desk" type="plane" pos="0 0 {args.desk_height}" size="0 0 0.05"
          material="desk" friction="1.0 0.01 0.001"/>
{chr(10).join(bodies)}
  </worldbody>
</mujoco>
"""
    out = REPO / args.out
    out.write_text(xml)
    print(f"wrote {out.relative_to(REPO)} with {len(args.objects)} object(s): {', '.join(args.objects)}")


if __name__ == "__main__":
    main()
